"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# CORE SETTINGS
# =========================
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-insecure-secret-key-change-me")

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# =========================
# HOSTS / SECURITY
# =========================
# Important: keep ONE ALLOWED_HOSTS definition (no duplicates).
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".herokuapp.com",  # allow any Heroku subdomain for this app
    "skillswap-hub-cstuart756.herokuapp.com",
    "skillswap-hub-cstuart756-df93470f789d.herokuapp.com",
]

# CSRF trusted origins (must include scheme)
CSRF_TRUSTED_ORIGINS = []
trusted = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in trusted.split(",") if o.strip()]
else:
    # Default to your Heroku URL so forms work when deployed
    CSRF_TRUSTED_ORIGINS = [
        "https://skillswap-hub-cstuart756.herokuapp.com",
        "https://skillswap-hub-cstuart756-df93470f789d.herokuapp.com",
    ]

# =========================
# APPLICATIONS
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "skills",
    "exchanges",
]

# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# =========================
# DATABASE
# =========================
db_url = os.getenv("DATABASE_URL", "")

if db_url:
    # Heroku Postgres
    DATABASES = {
        "default": dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    # Local SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =========================
# AUTH / LOGIN
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "skill_list"
LOGOUT_REDIRECT_URL = "skill_list"

# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGE_CODE = "en-gb"
TIME_ZONE = "Europe/London"
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# STATIC FILES (WHITENOISE)
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Optional but recommended for WhiteNoise caching/compression
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# =========================
# PROXY / SSL (HEROKU)
# =========================
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Only force HTTPS + secure cookies in production
SECURE_SSL_REDIRECT = (not DEBUG) and (os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True").lower() == "true")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
